#!/usr/bin/env bash
#
#  Licensed to Cloudera, Inc. under one or more contributor license
#  agreements.  See the NOTICE file distributed with this work for
#  additional information regarding copyright ownership.  Cloudera,
#  Inc. licenses this file to you under the Apache License, Version
#  2.0 (the "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

BASEDIR=`dirname ${0}`
BASEDIR=`cd ${BASEDIR}/..;pwd`

HUAHIN_OPTS="-server -Xmx256m -Xms256m -XX:ParallelGCThreads=2 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC"

HUAHIN_PORT=$BASEDIR/conf/port
HUAHIN_LOG=$BASEDIR/log/huahin-manager.log
HUAHIN_LIB=$BASEDIR/lib
HUAHIN_WEB=$BASEDIR/webapp
HUAHIN_PID=$BASEDIR/log/.pid

HUAHIN_JAR=`ls $HUAHIN_LIB/huahin-manager-*.jar`
HUAHIN_PORT=`cat $HUAHIN_PORT`

case $1 in
  start)
    echo "Starting huahin manager"
    java $HUAHIN_OPTS -Dhuahin.home=$BASEDIR -jar $HUAHIN_JAR $HUAHIN_WEB $HUAHIN_PORT >> $HUAHIN_LOG 2>&1 &
    echo $! > $HUAHIN_PID
    ;;
  stop)
    echo "Stopping huahin manager"
    if [ -e $HUAHIN_PID ];
    then
      PID=`cat $HUAHIN_PID`
      kill -KILL $PID
      rm -f $HUAHIN_PID
    fi
    ;;
  status)
        status -p ${HUAHIN_PID} huahin-manager
        exit $?
        ;;    
  restart)
    echo "Stopping huahin manager"
    if [ -e $HUAHIN_PID ];
    then
      PID=`cat $HUAHIN_PID`
      kill -KILL $PID
      rm -f $HUAHIN_PID
    fi

    echo "Starting huahin manager"
    java $HUAHIN_OPTS -Dhuahin.home=$BASEDIR -jar $HUAHIN_JAR $HUAHIN_WEB $HUAHIN_PORT >> $HUAHIN_LOG 2>&1 &
    echo $! > $HUAHIN_PID
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

